service:
  name: "Registration Payment Service" 
  token: "put_secure_random_string_here_for_api_token"
server:
  port: 9092
  read_timeout_seconds: 30
  write_timeout_seconds: 30
  idle_timeout_seconds: 120
database:
  use: mysql #or inmemory
  username: 'demouser'
  password: 'demopw'
  database: 'tcp(localhost:3306)/dbname'
  parameters:
    - 'charset=utf8mb4'
    - 'collation=utf8mb4_general_ci'
    - 'parseTime=True'
    - 'timeout=30s' # connection timeout
cors_disabled: false

